-- Disable RLS on tables where we haven't defined policies yet
-- This prevents the "infinite recursion" fallback or implicit deny while we transition
ALTER TABLE prestacoes_contas DISABLE ROW LEVEL SECURITY;
ALTER TABLE cursos DISABLE ROW LEVEL SECURITY;
ALTER TABLE turmas DISABLE ROW LEVEL SECURITY;
ALTER TABLE atividades DISABLE ROW LEVEL SECURITY;
ALTER TABLE inscricoes DISABLE ROW LEVEL SECURITY;
ALTER TABLE presencas DISABLE ROW LEVEL SECURITY;
ALTER TABLE certificados DISABLE ROW LEVEL SECURITY;
ALTER TABLE patrimonio_bens DISABLE ROW LEVEL SECURITY;
ALTER TABLE patrimonio_movimentacoes DISABLE ROW LEVEL SECURITY;
ALTER TABLE patrimonio_manutencoes DISABLE ROW LEVEL SECURITY;
ALTER TABLE ia_conversas DISABLE ROW LEVEL SECURITY;
ALTER TABLE ia_mensagens DISABLE ROW LEVEL SECURITY;
ALTER TABLE ia_acoes_pendentes DISABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;
